# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6ae089fcd1a25e026d2768c7d08b38f3"
name = "Product Manager"
application_url = "https://dander-partition-overfull.ngrok-free.dev"
embedded = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,write_inventory,read_locations"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://dander-partition-overfull.ngrok-free.dev/auth/callback"
]
